[package]
name = "wasm-blobstore"
version = "0.1.0"
authors = [""]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "wasm_blobstore"

[dependencies]
futures = "0.3"
form_urlencoded = "1.0"
wasmbus-rpc = "0.11"
wasmcloud-interface-httpserver = "0.9.0"
wasmcloud-interface-blobstore = "0.5.1"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
